name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          cd greetings
          echo "Installing Python dependencies..."
          ls -la
          pip install -r requirements.txt

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing app
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          cd greetings
          echo "Stopping previous PM2 app (if running)..."
          pm2 delete greetings-app-dev || true

      - name: Start app with PM2
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          cd greetings
          echo "Starting Flask app with PM2 on port 7001..."
          pm2 start app.py --name greetings-app-dev -- --port 7001

      - name: Check PM2 status
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          pm2 list

      - name: Wait for app to be ready
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          echo "Waiting 10 seconds..."
          sleep 10

      - name: Show PM2 logs
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          pm2 logs greetings-app-dev --lines 50

  tests-on-dev:
    name: Run Tests on Development Environment
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install test dependencies
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          cd test-framework
          echo "Installing test dependencies..."
          npm install

      - name: Run greetings tests
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          cd test-framework
          echo "Running greetings tests..."
          npm run greetings greetings_dev
