name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing all required dependencies..."
          if (Test-Path "requirements.txt") {
            try {
              pip install -r requirements.txt
            } catch {
              pip3 install -r requirements.txt
            }
          }
          else {
            echo "requirements.txt file not found."
          }
