name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    name: Deploy to Dev Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing app
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          echo "Stopping previous app..."
          pm2 delete greetings-app-dev & EXIT /B 0

      - name: Start app with PM2
        shell: powershell
        working-directory: greetings
        run: |
          echo "Starting greetings-app-dev on port 7001..."
          pm2 start app.py --name greetings-app-dev --interpreter python
          Start-Sleep -Seconds 10

      - name: Check PM2 status
        shell: powershell
        run: pm2 list

      - name: Show PM2 logs
        shell: powershell
        run: pm2 logs greetings-app-dev --lines 50

  tests-on-dev:
    name: Run Tests on Dev
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install dependencies
        shell: powershell
        working-directory: test-framework
        run: npm install

      - name: Run tests on dev
        shell: powershell
        working-directory: test-framework
        run: npm run greetings greetings_dev
