name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Print current working directory
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          echo "Current directory:"
          pwd

      - name: List files in greetings dir
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: greetings
        run: |
          echo "Contents of greetings directory:"
          ls -la

      - name: Install Python dependencies
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: greetings
        run: |
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing app
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: greetings
        run: |
          echo "Stopping existing PM2 app (if running)..."
          pm2 delete greetings-app-dev || true

      - name: Start app with PM2
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: greetings
        run: |
          echo "Starting greetings-app-dev on port 7001..."
          pm2 start app.py --name greetings-app-dev -- --port 7001

      - name: Check PM2 process status
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          pm2 list

      - name: Wait for app to be ready
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          echo "Waiting 10s for app to start..."
          sleep 10

      - name: Show PM2 logs
        shell: "C:/Program Files/Git/bin/bash.exe"
        run: |
          pm2 logs greetings-app-dev --lines 50

  tests-on-dev:
    name: Run Tests on Development Environment
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install test dependencies
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: test-framework
        run: |
          echo "Installing test dependencies..."
          npm install

      - name: Run greetings tests
        shell: "C:/Program Files/Git/bin/bash.exe"
        working-directory: test-framework
        run: |
          echo "Running greetings tests..."
          npm run greetings greetings_dev
