name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    name: Deploy to Dev
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop previous PM2 app
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          echo "Stopping old PM2 app..."
          pm2 delete greetings-app-dev || exit 0

      - name: Start PM2 app
        shell: powershell
        working-directory: greetings
        run: |
          echo "Starting app on port 7001..."
          $env:PORT=7001
          pm2 start app.py --name greetings-app-dev --interpreter python
          Start-Sleep -Seconds 10

  tests-on-dev:
    name: Test Dev
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install dependencies
        shell: powershell
        working-directory: test-framework
        run: npm install

      - name: Restart PM2 app (Dev)
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          echo "Restarting app before tests..."
          pm2 restart greetings-app-dev || exit 0
          Start-Sleep -Seconds 5

      - name: Run tests
        shell: powershell
        working-directory: test-framework
        run: npm run greetings greetings_dev

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop previous PM2 app
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 delete greetings-app-staging || exit 0

      - name: Start PM2 app
        shell: powershell
        working-directory: greetings
        run: |
          $env:PORT=7002
          pm2 start app.py --name greetings-app-staging --interpreter python
          Start-Sleep -Seconds 10

  tests-on-staging:
    name: Test Staging
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install dependencies
        shell: powershell
        working-directory: test-framework
        run: npm install

      - name: Restart PM2 app (Staging)
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 restart greetings-app-staging || exit 0
          Start-Sleep -Seconds 5

      - name: Run tests
        shell: powershell
        working-directory: test-framework
        run: npm run greetings greetings_staging

  deploy-to-preprod:
    name: Deploy to Preprod
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop previous PM2 app
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 delete greetings-app-preprod || exit 0

      - name: Start PM2 app
        shell: powershell
        working-directory: greetings
        run: |
          $env:PORT=7003
          pm2 start app.py --name greetings-app-preprod --interpreter python
          Start-Sleep -Seconds 10

  tests-on-preprod:
    name: Test Preprod
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install dependencies
        shell: powershell
        working-directory: test-framework
        run: npm install

      - name: Restart PM2 app (Preprod)
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 restart greetings-app-preprod || exit 0
          Start-Sleep -Seconds 5

      - name: Run tests
        shell: powershell
        working-directory: test-framework
        run: npm run greetings greetings_preprod

  deploy-to-prod:
    name: Deploy to Prod
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop previous PM2 app
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 delete greetings-app-prod || exit 0

      - name: Start PM2 app
        shell: powershell
        working-directory: greetings
        run: |
          $env:PORT=7004
          pm2 start app.py --name greetings-app-prod --interpreter python
          Start-Sleep -Seconds 10

  tests-on-prod:
    name: Test Prod
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone greetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install dependencies
        shell: powershell
        working-directory: test-framework
        run: npm install

      - name: Restart PM2 app (Prod)
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          pm2 restart greetings-app-prod || exit 0
          Start-Sleep -Seconds 5

      - name: Run tests
        shell: powershell
        working-directory: test-framework
        run: npm run greetings greetings_prod
