name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing all required dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing app (if any)
        shell: powershell
        working-directory: greetings
        continue-on-error: true
        run: |
          echo "Stopping existing app..."
          pm2 delete greetings-app-dev & EXIT /B 0

      - name: Start app with PM2
        shell: powershell
        working-directory: greetings
        run: |
          echo "Starting greetings-app-dev on port 7001..."
          pm2 start app.py --name greetings-app-dev --interpreter python -- --port 7001

      - name: Wait for app to start
        shell: powershell
        run: Start-Sleep -Seconds 10

      - name: Check PM2 process status
        shell: powershell
        run: pm2 list

  tests-on-dev:
    name: Run Tests on Development Environment
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install test dependencies
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Installing test dependencies..."
          npm install

      - name: Run greetings tests
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Running greetings tests..."
          npm run greetings greetings_dev
