name: Python Greetings Deployment

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Installing Python dependencies...
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing PM2 process
        shell: powershell
        working-directory: greetings
        run: |
          echo "Stopping existing PM2 process..."
          pm2 delete greetings-app-dev || echo "No existing process to delete"

      - name: Start app with PM2 on port 7001
        shell: powershell
        working-directory: greetings
        run: |
          echo "Starting greetings-app-dev on port 7001..."
          pm2 start app.py --name greetings-app-dev --interpreter python -- --port 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install npm dependencies
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Installing npm dependencies..."
          npm install

      - name: Running greetings tests...
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Running greetings tests..."
          npm run greetings greetings_dev
