name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          echo "Installing all required dependencies..."
          if (Test-Path "requirements.txt") {
            try {
              pip install -r requirements.txt
            }
            catch {
              pip3 install -r requirements.txt
            }
          } else {
            echo "requirements.txt file not found."
          }

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing app (if running)
        shell: powershell
        continue-on-error: true
        run: |
          echo "Stopping existing greetings-app-dev instance (if any)..."
          pm2 delete greetings-app-dev

      - name: Start greetings app
        shell: powershell
        working-directory: greetings
        run: |
          echo "Starting greetings-app-dev..."
          pm2 start app.py --name greetings-app-dev
          echo "Waiting for app to fully start..."
          Start-Sleep -Seconds 5

  tests-on-dev:
    name: Run Tests on Development Environment
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install test dependencies
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Installing Node.js test dependencies..."
          npm install

      - name: Run Mocha tests (greetings)
        shell: powershell
        working-directory: test-framework
        run: |
          echo "Running Mocha greetings tests against http://127.0.0.1:7001..."
          $env:BASE_URL="http://127.0.0.1:7001"
          npm run greetings greetings_dev
