name: Python Greetings Delivery Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        shell: powershell
        working-directory: greetings
        run: |
          Write-Output "Installing Python dependencies..."
          pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Stop existing PM2 process
        shell: powershell
        working-directory: greetings
        run: |
          Write-Output "Stopping existing PM2 process..."
          try { pm2 delete greetings-app-dev } catch { Write-Output "No existing process to delete" }

      - name: Start app with PM2 on port 7001
        shell: powershell
        working-directory: greetings
        run: |
          Write-Output "Starting greetings-app-dev on port 7001..."
          pm2 start app.py --name greetings-app-dev --interpreter python -- --port 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Install test dependencies
        shell: powershell
        working-directory: test-framework
        run: |
          Write-Output "Installing NPM test dependencies..."
          npm install

      - name: Run tests on dev environment
        shell: powershell
        working-directory: test-framework
        run: |
          Write-Output "Running greetings tests on dev..."
          npm run greetings greetings_dev
