name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        uses: ./.github/actions/install-deps

  deploy-to-dev:
    name: Deploy to Dev Environment
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Deploy Python app to Dev
        uses: ./.github/actions/deploy
        with:
          environment: dev
          port: 7001

  tests-on-dev:
    name: Run Tests on Dev
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Run tests on Dev
        uses: ./.github/actions/test
        with:
          env_tag: greetings_dev

  deploy-to-staging:
    name: Deploy to Staging Environment
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Deploy Python app to Staging
        uses: ./.github/actions/deploy
        with:
          environment: staging
          port: 7002

  tests-on-staging:
    name: Run Tests on Staging
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Run tests on Staging
        uses: ./.github/actions/test
        with:
          env_tag: greetings_stg

  deploy-to-preprod:
    name: Deploy to Preprod Environment
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Deploy Python app to Preprod
        uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: 7003

  tests-on-preprod:
    name: Run Tests on Preprod
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Run tests on Preprod
        uses: ./.github/actions/test
        with:
          env_tag: greetings_preprod

  deploy-to-prod:
    name: Deploy to Prod Environment
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Deploy Python app to Prod
        uses: ./.github/actions/deploy
        with:
          environment: prod
          port: 7004

  tests-on-prod:
    name: Run Tests on Prod
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework

      - name: Run tests on Prod
        uses: ./.github/actions/test
        with:
          env_tag: greetings_prod
